# Generated by Django 2.1.7 on 2019-06-02 19:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0010_parcedcompany_cb_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_long_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
