branch-defaults:
  master:
    environment: Itj-prod
environment-defaults:
  Itj-prod:
    branch: null
    repository: null
global:
  application_name: itj
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
