# Generated by Django 2.1.7 on 2019-04-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0004_auto_20190428_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyurl',
            name='url_type',
            field=models.CharField(choices=[('MAIN', 'Website'), ('LINKEDIN', 'LinkedIn'), ('ANGELCO', 'AngelList'), ('CRUNCHBASE', 'Crunchbase'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('GLASSDOOR', 'Glassdoor'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
    ]
