# Generated by Django 2.1.7 on 2019-04-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0006_auto_20190429_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='visa_sponsorhip',
        ),
        migrations.AddField(
            model_name='position',
            name='visa_sponsorhip',
            field=models.BooleanField(default=False),
        ),
    ]
