# Generated by Django 2.1.7 on 2019-04-29 17:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0008_auto_20190429_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pitch',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='keywords',
            field=models.ManyToManyField(through='mycatalog.PositionKeyword', to='mycatalog.Keyword'),
        ),
    ]
