# Generated by Django 2.1.7 on 2019-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0011_auto_20190429_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionkeyword',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='positionkeyword',
            name='keyword_ref',
        ),
        migrations.RemoveField(
            model_name='positionkeyword',
            name='position_name_ref',
        ),
        migrations.AlterField(
            model_name='position',
            name='keyword_ref',
            field=models.ManyToManyField(to='mycatalog.Keyword', verbose_name='Keywords'),
        ),
        migrations.DeleteModel(
            name='PositionKeyword',
        ),
    ]
