# Generated by Django 2.1.7 on 2019-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0017_auto_20190509_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyurl',
            name='url_type',
            field=models.CharField(choices=[('MAIN', 'Company Website'), ('LINKEDIN', 'LinkedIn'), ('ANGELCO', 'AngelList'), ('CRUNCHBASE', 'Crunchbase'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('GLASSDOOR', 'Glassdoor'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
    ]
