# Generated by Django 2.1.7 on 2019-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0019_auto_20190513_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyurl',
            name='url_text',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companyurl',
            name='url_type',
            field=models.CharField(choices=[('MAIN', 'Company Website'), ('LINKEDIN', 'LinkedIn'), ('ANGELCO', 'AngelList'), ('CRUNCHBASE', 'Crunchbase'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('GLASSDOOR', 'Glassdoor'), ('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
    ]
