# Generated by Django 2.1.7 on 2019-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0021_auto_20190513_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydomainsclassifier',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
