# Generated by Django 2.1.7 on 2019-06-02 19:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0023_auto_20190526_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_info',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
