# Generated by Django 2.1.7 on 2019-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0031_auto_20190616_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary_frequency',
            field=models.CharField(blank=True, choices=[('HOUR', 'per hour'), ('MONTH', 'per month'), ('YEAR', 'per year')], default='YEAR', max_length=20),
        ),
    ]
