# Generated by Django 2.1.7 on 2019-07-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0033_position_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPositionParsingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_rule', models.CharField(choices=[('POSITIONS_LIST', 'Positions list'), ('POSITION_NAME', 'Title'), ('POSITION_LOCATION', 'Location'), ('POSITION_DESCRIPTION', 'Description'), ('POSITION_DESCRIPTION_EXCLUDE', 'Description exclude')], max_length=100)),
                ('parsing_path', models.CharField(max_length=500)),
                ('company_name_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycatalog.Company')),
            ],
        ),
    ]
