# Generated by Django 2.1.7 on 2019-07-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0036_auto_20190720_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('category_name_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycatalog.Category', verbose_name='Category')),
            ],
        ),
    ]
