# Generated by Django 2.1.7 on 2019-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0038_keywordsynonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypositionparsingrule',
            name='parsing_path',
            field=models.CharField(max_length=1024),
        ),
    ]
