# Generated by Django 2.1.7 on 2019-05-07 19:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, unique=True)),
                ('company_logo_url', models.URLField(blank=True)),
                ('edited_date', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParcedPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=500)),
                ('position_slug', models.CharField(blank=True, max_length=500)),
                ('position_parced_id', models.CharField(max_length=100, unique=True)),
                ('epoch', models.CharField(blank=True, max_length=100)),
                ('position_datetime', models.DateTimeField()),
                ('job_description', ckeditor.fields.RichTextField(verbose_name='Job Description')),
                ('job_url', models.URLField(blank=True)),
                ('edited_date', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('company_name_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsparcer.ParcedCompanies', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='ParcedTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='parcedpositions',
            name='keyword_ref',
            field=models.ManyToManyField(to='jobsparcer.ParcedTags', verbose_name='Tags'),
        ),
    ]
