# Generated by Django 2.1.7 on 2019-05-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParcedCompanies',
            new_name='ParcedCompany',
        ),
        migrations.RenameModel(
            old_name='ParcedPositions',
            new_name='ParcedPosition',
        ),
        migrations.RenameModel(
            old_name='ParcedTags',
            new_name='ParcedTag',
        ),
        migrations.AlterModelOptions(
            name='parcedcompany',
            options={'verbose_name': 'Parced Company', 'verbose_name_plural': 'Parced Companies'},
        ),
        migrations.AlterModelOptions(
            name='parcedposition',
            options={'verbose_name': 'Parced Position', 'verbose_name_plural': 'Parced Positions'},
        ),
        migrations.AlterModelOptions(
            name='parcedtag',
            options={'verbose_name': 'Parced Tag', 'verbose_name_plural': 'Parced Tags'},
        ),
    ]
