# Generated by Django 2.1.7 on 2019-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0002_auto_20190507_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcedcompany',
            name='verified',
        ),
        migrations.AddField(
            model_name='parcedposition',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcedposition',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
