# Generated by Django 2.1.7 on 2019-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0003_auto_20190508_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcedcompany',
            name='moved_to_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcedposition',
            name='moved_to_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcedtag',
            name='moved_to_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
