# Generated by Django 2.1.7 on 2019-06-02 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0008_parcingparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_logo',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_short_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_web_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
