# Generated by Django 2.1.7 on 2019-06-02 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0009_auto_20190602_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_other',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
