# Generated by Django 2.1.7 on 2019-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsparcer', '0011_parcedcompany_cb_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcedcompany',
            name='cb_check',
            field=models.BooleanField(default=False),
        ),
    ]
