# Generated by Django 2.1.7 on 2019-04-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0002_auto_20190427_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='offices_locations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
