# Generated by Django 2.1.7 on 2019-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0003_auto_20190427_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date edited'),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_people',
            field=models.CharField(blank=True, choices=[('TEN', '1-10'), ('FIFTY', '11-50'), ('HUNDRED', '51-100'), ('HUNDRED', '101-500'), ('THOUSAND', '501-1000'), ('LARGE', '>1000')], max_length=20),
        ),
        migrations.AlterField(
            model_name='companyurl',
            name='url_type',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('LINKEDIN', 'LINKEDIN'), ('ANGELCO', 'ANGELCO'), ('CRUNCHBASE', 'CRUNCHBASE'), ('FACEBOOK', 'FACEBOOK'), ('TWITTER', 'TWITTER'), ('GLASSDOOR', 'GLASSDOOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
    ]
