# Generated by Django 2.1.7 on 2019-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0007_auto_20190429_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='visa_sponsorhip',
            new_name='visa_sponsorship',
        ),
    ]
