# Generated by Django 2.1.7 on 2019-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0009_auto_20190429_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDomainsClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='domain_name',
            field=models.ManyToManyField(to='mycatalog.CompanyDomainsClassifier'),
        ),
    ]
