# Generated by Django 2.1.7 on 2019-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0016_auto_20190509_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
