# Generated by Django 2.1.7 on 2019-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0020_auto_20190513_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyurl',
            name='url_type',
            field=models.CharField(choices=[('MAIN', 'Company Website'), ('LINKEDIN', 'LinkedIn'), ('ANGELCO', 'AngelList'), ('CRUNCHBASE', 'Crunchbase'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('GLASSDOOR', 'Glassdoor'), ('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('STACKOVERFLOW', 'Stackoverflow'), ('GITHUB', 'GitHub'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
    ]
