# Generated by Django 2.1.7 on 2019-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0024_company_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='work_worldwide',
            field=models.BooleanField(default=False),
        ),
    ]
