# Generated by Django 2.1.7 on 2019-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0025_position_work_worldwide'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_id_redirect_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID redirect to'),
        ),
    ]
