# Generated by Django 2.1.7 on 2019-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0027_auto_20190609_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='count_apply',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Applies'),
        ),
        migrations.AlterField(
            model_name='position',
            name='count_view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Views'),
        ),
    ]
