# Generated by Django 2.1.7 on 2019-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0028_auto_20190613_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
