# Generated by Django 2.1.7 on 2019-07-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0037_categorykeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=100, unique=True)),
                ('keyword_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycatalog.Keyword', verbose_name='Keyword')),
            ],
        ),
    ]
