# Generated by Django 2.1.7 on 2019-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0039_auto_20190801_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypositionparsingrule',
            name='parsing_rule',
            field=models.CharField(choices=[('USE_SELENIUM', 'Use selenuim for parsing'), ('POSITIONS_LIST', 'Positions list'), ('POSITIONS_LIST_IFRAME', 'Positions list inside IFRAME'), ('POSITIONS_LIST_EXCLUDE', 'Positions list exclude'), ('POSITIONS_LIST_URL_PREFIX', 'Positions list URL prefix'), ('POSITION_IFRAME', 'Position IFRAME path'), ('POSITION_NAME', 'Title'), ('POSITION_LOCATION', 'Location'), ('POSITION_DESCRIPTION', 'Description'), ('POSITION_DESCRIPTION_EXCLUDE', 'Description exclude')], max_length=100),
        ),
    ]
